services:
  valhalla:
    build:
      context: .
      args:
        DOWNLOAD_PBF: "true"
    image: valhalla-portugal:latest
    container_name: valhalla
    restart: unless-stopped

    ports:
      - "127.0.0.1:8002:8002"

    volumes:
      - ./custom_files:/custom_files

    environment:
      - server_threads=4
      - serve_tiles=True
      - use_tiles_ignore_pbf=False
      - tileset_name=valhalla_tiles
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False
      - build_transit=False
      - build_tar=True
      - force_rebuild=False
      - update_existing_config=True
      - TZ=Europe/Lisbon
